Repository CSCfi/etsin-ops, pull requests merged in 2020-12, with the labels that each got.

#41 CSCFAIRADM-436: Replace "FairCentOS" with CentOS 7
  Makefile
  Vagrantfile
  scripts/Vagrantfile.box
  scripts/update-box
  scripts/vagrant
  scripts/vagrant.pub
Labels: bugfix

#45 CSCFAIRMETA-801: Support separate internal and public download service urls
  ansible/inventories/local_development/group_vars/all
  ansible/roles/app_config/templates/app_config
Labels: new feature

#46 CSCFAIRMETA-821: Refactor SSO & SAML
  .gitignore
  ansible/inventories/local_development/group_vars/all
  ansible/roles/app_config/templates/app_config
  ansible/roles/certificates/tasks/main.yml
Labels: refactor-improve

#47 CSCFAIRMETA-834: Feature flags
  ansible/inventories/local_development/group_vars/all
  ansible/roles/app_config/templates/app_config
Labels: new feature
